# Generated by Django 5.1.3 on 2024-12-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alertasusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterDistancia',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_distancia', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterHT',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_ht', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterLluvia',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_lluvia', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterLUX',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_lux', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterMQ7',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_mq7', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterMQ8',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_mq8', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterPH',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_ph', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTC',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_tc', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTDS',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_tds', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTF',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_tf', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTS',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt_ts', models.IntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
