# Generated by Django 5.1.3 on 2024-12-04 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alertasusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cnt', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterDistancia',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntDistancia', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterHT',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntHT', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterLluvia',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntLluvia', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterLUX',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntLUX', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterMQ7',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntMQ7', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterMQ8',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntMQ8', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterPH',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntPH', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTC',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntTC', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTDS',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntTDS', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTF',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntTF', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CounterTS',
            fields=[
                ('nodo', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('cntTS', models.FloatField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
