# Generated by Django 5.1.3 on 2024-12-06 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_riego_cosecha_tiempo_cosecha_insumo_fecha_insumo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosecha',
            name='siembra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.siembra'),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='cultivo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cultivo'),
        ),
        migrations.AlterField(
            model_name='siembra',
            name='parcela',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.parcela'),
        ),
    ]
