# Generated by Django 5.1.3 on 2024-12-06 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_cosecha_siembra_alter_siembra_cultivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='siembra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.siembra'),
        ),
    ]
