# Generated by Django 5.1.3 on 2025-05-22 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_tratamiento_siembra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aplicacioninsumo',
            name='fecha_aplicacion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='clima',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tratamiento',
            name='fecha_tratamiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
